### ISSUE TITLE
Problem with my first page..

### ISSUE THREAD

**Issue by andreataba** [alexlatchford/phpSesame#1]
Hi, I'm trying to use the phpSesame tool and I write this page to query my semantic repository. 
My repository is composed by Sesame and SwiftOwlim..

My php code is: 

<head>
<body>
<?php 
require_once "phpSesame.php";
$sesame = array ('url' => 'http://localhost:8080/openrdf-sesame', 'repository' => 'andrea');
$store = new phpSesame($sesame['url'], $sesame['repository']); 
$sparql = 'PREFIX owl: PREFIX rdf: SELECT \* { ?CIRC rdf:type "Circolari" }';
$resultFormat = phpSesame::SPARQL_XML;  
$lang = "sparql";  
$infer = true; 
$result = $store->query($sparql, $resultFormat, $lang, $infer); 
echo $result;
?>
</body>
</head>

I don't receive any response in output

anyone can help me?? 

thanks

**Comment by alexlatchford** [comment]
Hello,

The result is returned in a result object instead of using echo you 
should try to use:

print_r($result->getRows());

If this does not work I would suggest look at whether the sparql query 
you are using is generating results by performing it in the Workbench, 
that is a problem I regularly have!

Thanks,
Alex

**Comment by alexlatchford** [comment]
I'd also suggest using a try/catch block to catch any exceptions that the library throws.. This should also help you to highlight any problems you are having.

**Comment by andreataba** [comment]
The SPARQL query give me a good result in workbench so I suppose that it's correct.  
I try to use print_r command but there are no results on the page. 
I'm using gedit on linux to edit the php files.. so I can't block the code execution to highlight the problems..but I think that the problem may be in the first three lines because if I try to echo the sparql var ($sparql).. it doesn't print any text in the page..
I never use the try/catch block in php.. how does it works?

**Comment by alexlatchford** [comment]
I'd suggest reading about Exceptions before continuing, there are lots of documents across the web about these. http://php.net/manual/en/language.exceptions.php

If it is failing there it is probably because you don't have the dependencies the library requires, have you installed HTTP_Request2 and do you have that configured properly?

**Comment by andreataba** [comment]
the problem was in installing pear and http_Request2.. 
I reinstall it and now it works perfectly.. I read in output the array with the triple results of SPARQL Query.. 
It seems to be perfect for my semantic Web project that I try to develop for my master's thesis.. 
Thanks for your work and your support!!

**Comment by andreataba** [comment]
I have one more question.. 
My specific needs of the application require the results in sparqlXML format. 
Now I have the triple in a object. 
XML is stored in a php var ? or I have to built a transformation from the object to XML?

**Comment by alexlatchford** [comment]
Do you mean inserting or updating data? The wiki page explains how the library handles this.

**Comment by andreataba** [comment]
No sorry, I try to explain better..  I mean the sparql-result+xml document that sesame give as response of the request.. 
I need to have the SPARQL results that now I have in the array in php in XML format.. it's possible?
because I need to apply a xslt transformation to the xml file..

**Comment by alexlatchford** [comment]
In the current version there isn't a function in the results handler to expose the raw XML data which is returned, but there is a member variable it is loaded into I believe. If you would like to write in the function and submit a patch I'd happily merge it into the master branch.

**Comment by andreataba** [comment]
Yes sure..I'll try to realize it.. 
Thank you

__

Andrea Tabarelli de Fatis
Inviato da iPhone

__

Il giorno 10/mag/2011, alle ore 15:10, alexlatchfordreply@reply.github.com ha scritto:
